install:
- pip install --user awscli
- wget https://github.com/gohugoio/hugo/releases/download/v0.68.0/hugo_0.68.0_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version
before_script:
- rm -rf public
- hugo
script:
- aws configure set AWS_ACCESS_KEY_ID $ACCESS_KEY_ID
- aws configure set AWS_SECRET_ACCESS_KEY $SECRET_ACCESS_KEY
- aws s3 sync public/ s3://www.valuableknowledge.tk --acl public-read --delete --exclude 'videosforastr1/*' --exclude 'favicon.ico' --exclude 'apple-touch-icon.png' 
- aws cloudfront create-invalidation --distribution-id E3I6YDZ6JUUPVO --paths '/*'
branches:
    only:
      - master