baseurl = "./"
languageCode = "en-us"
title = "Mysterious Unicorn's Blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

relativeURLs = true
uglyURLs = true


[params]
    site_author = "Mysterious Unicorn"
    site_description = "The Awesome Blog of the Mysterious Unicorn!"
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/unicorn-3637428.png"
    header_background = "img/unicornnebula.jpg"
    header_title = "Blog of the Mysterious Unicorn!"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""
